QUESTIONS = [
    "What is machine learning?",
    "Explain the difference between supervised and unsupervised learning.",
    "What is overfitting, and how can it be prevented?",
    "Describe the working of a decision tree.",
    "What is the bias-variance tradeoff?",
    "What are the different types of machine learning?",
    "What is reinforcement learning? Provide an example.",
    "What is feature engineering, and why is it important?",
    "How does principal component analysis (PCA) work?",
    "Explain the difference between bagging and boosting.",
    "What is a confusion matrix, and how is it used?",
    "What are precision, recall, and F1-score?",
    "What is the difference between L1 and L2 regularization?",
    "Explain the concept of cross-validation.",
    "What is gradient descent, and how does it work?",
    "What are the different types of gradient descent algorithms?",
    "What is backpropagation in neural networks?",
    "Explain the vanishing and exploding gradient problem.",
    "What is a convolutional neural network (CNN), and where is it used?",
    "Describe the architecture of a recurrent neural network (RNN).",
    "What is the difference between RNN and LSTM?"
]