# Generated by Django 4.2.5 on 2025-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_chat', '0004_user_disease_user_disease_level_user_parents_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
