# Generated by Django 4.2.5 on 2025-02-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_chat', '0008_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
